name: 'PMS ticket mover'
description: 'Moves tickets on the PMS based on some interactions with the VCS'
inputs:
    pms:
        description: Select the PMS you want to interact with
        required: true
        default: 'jira'
    desired_status:
        description: Status where you want to put the ticket
        required: true
    trello_token:
        description: Trello authenticated token
        required: false
    trello_app_key:
        description: Trello app key
        required: false
    youtrack_base_url:
        description: YouTrack URL
        required: false
    youtrack_token:
        description: YouTrack Token
        required: false
runs:
    using: 'node12'
    main: 'index.js'